<?php
//
// $Revision: 3.0 $
// $Date: 2016/03/14 22:56:41 $
//
// bluealliance.inc
//
// Functions and field mappings to be used for The Blue Alliance API
//


// ***************************
//
// Tablet Sync Library 
//

// $tablet_templates = "../tablet/templates";
// $tablet_ingest = "../tablet/ingest";
// $tablet_ingest_complete = "../tablet/ingest-complete";
// $tablet_teamimages = "../tablet/team_images";


//
// function: tba() - 
//   $
//
//




//
// ****************************************************************************
//
// end of tabletsync.inc -- do not leave any lines under the end of this closure
?>